# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Siggy < Formula
  desc "Generate presigned URL for AWS S3"
  homepage "https://github.com/RyuyaIshibashi/homebrew-aws-s3-siggy"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RyuyaIshibashi/aws-s3-siggy/releases/download/v0.1.0/siggy_Darwin_x86_64.tar.gz"
      sha256 "c2853cf87724b795e5da6e6eebd92bb089001111f2a162a2dd02cdbfce6e6391"

      def install
        bin.install "siggy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RyuyaIshibashi/aws-s3-siggy/releases/download/v0.1.0/siggy_Darwin_arm64.tar.gz"
      sha256 "97886728ff21e1a0e33bd284edddd9518e21cb1a2beace0681c8905f40437978"

      def install
        bin.install "siggy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/RyuyaIshibashi/aws-s3-siggy/releases/download/v0.1.0/siggy_Linux_x86_64.tar.gz"
      sha256 "a84193407f6d466c4499c0d635f94381fa61931f9dc7b2870d37c7be77f2be46"
      def install
        bin.install "siggy"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/RyuyaIshibashi/aws-s3-siggy/releases/download/v0.1.0/siggy_Linux_arm64.tar.gz"
      sha256 "7d4fa04a5919c990f99370d1368c6ded4b818a7c09eb34510632d2bf03f7f95a"
      def install
        bin.install "siggy"
      end
    end
  end
end
