# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Siggy < Formula
  desc "Generate presigned URL for AWS S3"
  homepage "https://github.com/RyuyaIshibashi/homebrew-aws-s3-siggy"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RyuyaIshibashi/aws-s3-siggy/releases/download/v0.1.0/siggy_Darwin_x86_64.tar.gz"
      sha256 "6d0fd14e2232a402c1eb6312d1cde0070120b9256b0edf7148e504758d1e083a"

      def install
        bin.install "siggy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RyuyaIshibashi/aws-s3-siggy/releases/download/v0.1.0/siggy_Darwin_arm64.tar.gz"
      sha256 "b968775e70a06609511e1129f06914253adc3d761c4c79c9965eec046b3ac95d"

      def install
        bin.install "siggy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/RyuyaIshibashi/aws-s3-siggy/releases/download/v0.1.0/siggy_Linux_x86_64.tar.gz"
      sha256 "d866c0829dae5144d9725c51c700779d3cf65f5463bf6ca73e10e1407a804f09"
      def install
        bin.install "siggy"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/RyuyaIshibashi/aws-s3-siggy/releases/download/v0.1.0/siggy_Linux_arm64.tar.gz"
      sha256 "e3eb67576a722963a7d32eff798240cb20c3dd24bf4ec86557418ec7afbd5667"
      def install
        bin.install "siggy"
      end
    end
  end
end
